# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtPnWq9SOYO9rF0fMFNvEhhMntgXKit2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

# 🔄 Step 1: Generating Raw Telecom/SaaS Subscriber Data
raw_data = {
    'Customer_ID': list(range(1001, 1013)),
    'Subscription_Type': ['Monthly', 'Annual', 'Monthly', ' Monthly ', 'Annual', 'Monthly', 'Annual', 'Monthly', 'Monthly', ' Annual', 'Monthly', 'Annual'],
    'Tenure_Months': [3, 24, 1, 12, 36, 5, 18, 2, 8, 4, 15, 48],
    'Monthly_Bill_INR': ['1499', '899', 'missing', '1299', '799', '1499', '899', '1499', '1199', '799', '1299', '699'],
    'Support_Tickets_Opened': [5, 1, 4, 2, 0, 6, 1, 3, 2, 7, 3, 0],
    'Churned': [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0] # 1 = Cancelled, 0 = Active
}

df = pd.DataFrame(raw_data)

# 🔄 Step 2: Executing Data Cleaning & Standardization
df['Subscription_Type'] = df['Subscription_Type'].str.strip()
df['Monthly_Bill_INR'] = pd.to_numeric(df['Monthly_Bill_INR'], errors='coerce')
bill_median = df['Monthly_Bill_INR'].median()
df['Monthly_Bill_INR'] = df['Monthly_Bill_INR'].fillna(bill_median)

# 📊 Step 3: Compiling MIS Executive Revenue Risk Report
total_customers = len(df)
churned_customers = df['Churned'].sum()
churn_rate = (churned_customers / total_customers) * 100
total_mrr = df['Monthly_Bill_INR'].sum()
mrr_at_risk = df[df['Churned'] == 1]['Monthly_Bill_INR'].sum()

print("📊 --- MIS REVENUE RISK REPORT --- 📊")
print(f"👥 Total Monitored Accounts: {total_customers}")
print(f"📉 Customer Churn Rate: {churn_rate:.1f}%")
print(f"💰 Total Monthly Revenue Portfolio: INR {total_mrr:,.2f}")
print(f"⚠️ Urgent MRR Revenue At Risk: INR {mrr_at_risk:,.2f}")
print("-" * 45)

# 🤖 Step 4: Training ML Customer Risk Predictor
X = df[['Monthly_Bill_INR', 'Support_Tickets_Opened']].values
y = df['Churned'].values

model = LogisticRegression()
model.fit(X, y)

# Predict risk for a high-value customer opening lots of complaints
at_risk_customer = np.array([[1499, 5]])
prediction = model.predict(at_risk_customer)[0]
risk_status = "CRITICAL CHURN RISK" if prediction == 1 else "STABLE ACCOUNT"
print(f"🔮 ML Risk Audit: High-ticket user with active complaints -> {risk_status}\n")

# 🖼️ Step 5: Visualizing Trends Live in the Notebook
plt.figure(figsize=(9, 5))
sns.set_theme(style="darkgrid")

sns.scatterplot(data=df, x='Monthly_Bill_INR', y='Support_Tickets_Opened',
                hue='Churned', palette={0: '#2ecc71', 1: '#E74C3C'}, s=140)

plt.title("MIS Executive Dashboard: Subscription Revenue Risk Vectors", fontsize=13, fontweight='bold')
plt.xlabel("Monthly Bill Amount (INR)", fontsize=11)
plt.ylabel("Customer Support Tickets Opened", fontsize=11)
plt.legend(title='Account Status', labels=['Active Subscriber', 'Cancelled/Churned'])

# Display chart instantly inside the Colab window
plt.show()

